### ISSUE TITLE
certain RPL and ERR not appearing in clients' terminal

### ISSUE THREAD

**Issue by aloysiusv** [benjaminbrassart/ft_irc#81]
If [ /mode #nonexistentchan +i  ], NOSUCHCHANNEL doesn't appear on client's side.

If [ /mode user ], RPL_UMODEIS doesn't appear on client's side.

If [ /mode #nonexistentchan +i  ], NOSUCHCHANNEL doesn't appear on client's side.

No message if new ChanOp has been promoted (but maybe that's normal).

**Comment by aloysiusv** [comment]
if [ /kill user], ERR_NOPRIVILEGE doesn't appear on client's side.

**Comment by benjaminbrassart** [comment]
> If [ /mode #nonexistentchan +i ], NOSUCHCHANNEL doesn't appear on client's side.
> 
> If [ /mode user ], RPL_UMODEIS doesn't appear on client's side.
> 
> If [ /mode #nonexistentchan +i ], NOSUCHCHANNEL doesn't appear on client's side.
> 
> No message if new ChanOp has been promoted (but maybe that's normal).

Messages do appear, only in the main thread of irssi

> if [ /kill user], ERR_NOPRIVILEGE doesn't appear on client's side.

Same here

**Comment by benjaminbrassart** [comment]
> No message if new ChanOp has been promoted (but maybe that's normal).

The message appears but is incomplete. See #82

**Comment by aloysiusv** [comment]
Fixed in #82
